resources:
  - k8s/cronjob.yaml
namespace: octoflux
configMapGenerator:
  - name: octoflux-config
    envs:
      - conf/octoflux.conf
secretGenerator:
  - name: octoflux-secret
    envs:
     - conf/secrets.conf
