apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-octoflux
spec:
  schedule: "0,30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: octoflux
            image: ghcr.io/iainlane/octoflux:latest
            args: ["--debug"]
            envFrom:
            - configMapRef:
                name: octoflux-config
            - secretRef:
                name: octoflux-secret
            imagePullPolicy: Always
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
